# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

[sncast.katana]
url = "http://127.0.0.1:5050"
# accounts_file = "../account-file"
account = "katana-test"
# keystore = "~/keystore"
wait_params = { timeout = 500, retry_interval = 10 }
block_explorer = "Voyager"

[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
# accounts_file = "../account-file"
account = "starkparking"
# keystore = "~/keystore"
wait_params = { timeout = 500, retry_interval = 10 }
block_explorer = "Voyager"